version: '3.8'

services:
  csharp-app:
    image: vilkan32/delinian-api:c7ed4f377a991bf26d7dff68ac62e703053dc291
    build:
      context: ./Delinian
    ports:
      - "80:80"
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=YourDatabase;User=sa;Password=YourPassword123!

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      - SA_PASSWORD=YourPassword123!
      - ACCEPT_EULA=Y
      - MSSQL_USER=YourUser
      - MSSQL_PASSWORD=YourPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:
